name: sdomirea
description: Mirea SDO Application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  html: ^0.15.1
  loading_animation_widget:
  shimmer: ^2.0.0
  url_launcher: ^6.1.6
  open_file: ^3.2.1
  shared_preferences: ^2.0.15
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  dio: ^4.0.6

flutter:
  assets:
    - assets/images/
  uses-material-design: true